#!/usr/bin/env bash

if
  [[ -s "/home/thanhcongframgia/.rvm/gems/ruby-1.9.3-p547/environment" ]]
then
  source "/home/thanhcongframgia/.rvm/gems/ruby-1.9.3-p547/environment"
  exec tilt "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/thanhcongframgia/.rvm/gems/ruby-1.9.3-p547/environment'" >&2
  exit 1
fi
