# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1404207825);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1404207945);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1404207705);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "messagingmenu%40mozilla.com:1.3.1,edsintegration%40mozilla.com:0.5,globalmenu%40ubuntu.com:3.6.4,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:17.0.8");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1377021532000},\"messagingmenu@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"mtime\":1375576694000},\"edsintegration@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/edsintegration@mozilla.com.xpi\",\"mtime\":1375576695000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/globalmenu@ubuntu.com\",\"mtime\":1377021532000}}}]");
user_pref("extensions.lastAppVersion", "17.0.8");
user_pref("extensions.lastPlatformVersion", "17.0.8");
user_pref("extensions.pendingOperations", false);
user_pref("idle.lastDailyNotification", 1404208614);
user_pref("intl.charsetmenu.mailview.cache", "UTF-8");
user_pref("ldap_2.servers.eds.description", "EDS Address Book Bootstrapper");
user_pref("ldap_2.servers.eds.dirType", 3);
user_pref("ldap_2.servers.eds.filename", "eds.mab");
user_pref("ldap_2.servers.eds.position", 1);
user_pref("ldap_2.servers.eds.uri", "moz-abedsdirectory://");
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.account.lastKey", 2);
user_pref("mail.accountmanager.accounts", "account1,account2");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.accountmanager.localfoldersserver", "server2");
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.identity.id1.draft_folder", "mailbox://duong.thanh.cong@framgia.com/Drafts");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "0");
user_pref("mail.identity.id1.fcc_folder", "mailbox://duong.thanh.cong@framgia.com/Sent");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "0");
user_pref("mail.identity.id1.fullName", "duong thanh cong");
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.stationery_folder", "mailbox://duong.thanh.cong@framgia.com/Templates");
user_pref("mail.identity.id1.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id1.useremail", "duong.thanh.cong@framgia.com");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.rights.version", 1);
user_pref("mail.root.none", "/home/thanhcongframgia/.thunderbird/oe4atqih.default/Mail");
user_pref("mail.root.none-rel", "[ProfD]Mail");
user_pref("mail.root.pop3", "/home/thanhcongframgia/.thunderbird/oe4atqih.default/Mail");
user_pref("mail.root.pop3-rel", "[ProfD]Mail");
user_pref("mail.server.server1.check_new_mail", true);
user_pref("mail.server.server1.delete_by_age_from_server", true);
user_pref("mail.server.server1.delete_mail_left_on_server", true);
user_pref("mail.server.server1.directory", "/home/thanhcongframgia/.thunderbird/oe4atqih.default/Mail/framgia.com");
user_pref("mail.server.server1.directory-rel", "[ProfD]Mail/framgia.com");
user_pref("mail.server.server1.download_on_biff", true);
user_pref("mail.server.server1.hostname", "framgia.com");
user_pref("mail.server.server1.leave_on_server", true);
user_pref("mail.server.server1.login_at_startup", true);
user_pref("mail.server.server1.name", "duong.thanh.cong@framgia.com");
user_pref("mail.server.server1.num_days_to_leave_on_server", 14);
user_pref("mail.server.server1.socketType", 2);
user_pref("mail.server.server1.spamActionTargetAccount", "mailbox://duong.thanh.cong@framgia.com");
user_pref("mail.server.server1.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server1.type", "pop3");
user_pref("mail.server.server1.userName", "duong.thanh.cong");
user_pref("mail.server.server2.directory", "/home/thanhcongframgia/.thunderbird/oe4atqih.default/Mail/Local Folders");
user_pref("mail.server.server2.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server2.hostname", "Local Folders");
user_pref("mail.server.server2.name", "Local Folders");
user_pref("mail.server.server2.spamActionTargetAccount", "mailbox://nobody@Local%20Folders");
user_pref("mail.server.server2.storeContractID", "@mozilla.org/msgstore/berkeleystore;1");
user_pref("mail.server.server2.type", "none");
user_pref("mail.server.server2.userName", "nobody");
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.hostname", "framgia.com");
user_pref("mail.smtpserver.smtp1.port", 587);
user_pref("mail.smtpserver.smtp1.try_ssl", 2);
user_pref("mail.smtpserver.smtp1.username", "duong.thanh.cong");
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 5);
user_pref("mailnews.database.global.datastore.id", "b471e92e-3e21-4d09-b998-86a743169d6");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "17.0.8");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
